CREATE TABLE SW_DICT(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    TYPE VARCHAR(128)    COMMENT '类型' ,
    LABEL VARCHAR(128)    COMMENT '标签' ,
    DESCRIPTION VARCHAR(128)    COMMENT '描述' ,
    VALUE VARCHAR(128)    COMMENT '值' ,
    SORT INT(1)    COMMENT '排序' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '字典表 ';/*SQL@Run*/

CREATE TABLE SW_USER(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    NAME VARCHAR(128)    COMMENT '用户名' ,
    PASSWORD VARCHAR(1024)    COMMENT '密码' ,
    INTINACY_NAME VARCHAR(128)    COMMENT '亲密昵称' ,
    COMMUNITY_NAME VARCHAR(128)    COMMENT '社区昵称' ,
    SALT VARCHAR(64)    COMMENT '盐' ,
    LOVER_ID VARCHAR(32)    COMMENT '情侣ID' ,
    TITLE_URL VARCHAR(1024)    COMMENT '头像地址 头像地址' ,
    SEX INT    COMMENT '性别 0女1男' ,
    DECLARATION VARCHAR(1024)    COMMENT '宣言' ,
    IS_SINGLE INT(1)   DEFAULT 1 COMMENT '是否单身 0未单身1单身' ,
    IS_MATCH INT(1)   DEFAULT 0 COMMENT '是否匹配过 0未匹配1匹配' ,
    DEL_FLAG INT(1)   DEFAULT 0 COMMENT '删除标识 0未删除1删除' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_DATE DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户表 ';/*SQL@Run*/

CREATE TABLE SW_USER_LOVE(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    BOY_ID VARCHAR(32)    COMMENT '男孩ID' ,
    GIRL_ID VARCHAR(32)    COMMENT '女孩ID' ,
    LOVE_DESCRIP VARCHAR(1024)    COMMENT '恋爱宣言' ,
    LOVE_SCORE INT(11)    COMMENT '恋爱分数' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '另一半关联表 ';/*SQL@Run*/

CREATE TABLE SW_LOVE_GALLERY(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    LOVE_ID VARCHAR(32)    COMMENT 'LOVE_ID' ,
    PHOITO_URL VARCHAR(1024)    COMMENT '照片地址' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '情侣相册 ';/*SQL@Run*/

CREATE TABLE SW_LOVE_DIARY(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    LOVE_ID VARCHAR(32)    COMMENT 'LOVE_ID' ,
    CONYENT VARCHAR(3072)    COMMENT '内容' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '情侣日记 ';/*SQL@Run*/

CREATE TABLE SW_LOVE_MEMORY(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    LOVE_ID VARCHAR(32)    COMMENT 'LOVE_ID' ,
    CONTENT VARCHAR(1024)    COMMENT '纪念标题' ,
    MEMORY_DATE DATETIME    COMMENT '纪念时间' ,
    LUNAR INT(1)    COMMENT '农历公历 0农历1公历' ,
    BACK_URL VARCHAR(1024)    COMMENT '背景地址' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '情侣纪念日 ';/*SQL@Run*/

CREATE TABLE SW_PUNCH(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    CONTENT VARCHAR(128)    COMMENT '打卡内容' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '打卡内容 ';/*SQL@Run*/

CREATE TABLE SW_PUNCH_LOVE(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    PUNCH_ID VARCHAR(32)    COMMENT '打卡ID' ,
    USER_ID VARCHAR(32)    COMMENT '用户ID' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '情侣打卡 ';/*SQL@Run*/

CREATE TABLE SW_ARTICLE_COLLECT(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    USER_ID VARCHAR(32)    COMMENT '用户ID' ,
    ARTICLE_ID VARCHAR(32)    COMMENT '文章ID' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '收藏文章 ';/*SQL@Run*/

CREATE TABLE SW_ARTICLE_LABLE(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    NAME VARCHAR(128)    COMMENT '标签名称' ,
    ENNAME VARCHAR(128)    COMMENT '标签英文名' ,
    DESCRI VARCHAR(128)    COMMENT '标签描述' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '文章标签 ';/*SQL@Run*/

CREATE TABLE SW_ARTICLE(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    TITLE VARCHAR(128)    COMMENT '标题' ,
    CONTENT VARCHAR(3072)    COMMENT '内容' ,
    REVIEW_NUM INT(11)    COMMENT '评论数量' ,
    THUMB_NUM INT(11)    COMMENT '点赞数量' ,
    ARTICLE_TYPE INT(1)   DEFAULT 0 COMMENT '文章类型 0为帖子，1为盖楼' ,
    FORBIDDEN_REVIEW INT(1)   DEFAULT 0 COMMENT '禁止评论 0不禁止，1禁止' ,
    CREATE_USER_PURL VARCHAR(1024)    COMMENT '发布人头像地址' ,
    CREATE_USER_SEX INT(1)    COMMENT '发布人性别' ,
    CREATE_USER_NAME VARCHAR(128)    COMMENT '发布人名称' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '文章表 ';/*SQL@Run*/

CREATE TABLE SW_ARTICLE_ANSWER(
    ID VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    ARTICLE_ID VARCHAR(32)    COMMENT '回复帖子ID' ,
    CONTENT VARCHAR(3072)    COMMENT '回复内容' ,
    ANSWER_ID VARCHAR(32)    COMMENT '回复人ID' ,
    ANSWER_NAME VARCHAR(128)    COMMENT '回复人名称' ,
    ANSWER_TYPE INT(1)    COMMENT '回复类型 0为回复帖子1为回复回复' ,
    TARGET_ID VARCHAR(32)    COMMENT '目标人ID' ,
    DEL_FLAG INT(1)    COMMENT '删除标识 0未删除1删除' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_DATE DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '文章回复表 ';/*SQL@Run*/





